// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type AppSettings = { port: number; interceptSsl: boolean; isBlocked: boolean; theme: string; scripts: ScriptConfig[]; sslExceptionPatterns: string[]; scriptsEnabled: boolean }

export type FilterConfig = { id: string; filterProtocol: string; filterHost: string; filterPort: string; filterPath: string; filterQuery: string }

export type HistoryEntry = { request: ProxyEvent; response: ProxyEvent | null }

export type ProxyEvent = { id: string; script_id: string; timestamp: string; method: string; uri: string; headers: ([string, string])[]; is_response: boolean; status: number | null; body: number[] | null }

export type ScriptConfig = { id: string; name: string; pattern: string; description?: string | null; code: string; enabled: boolean; compileError?: string | null; filters: FilterConfig[] }

export type ScriptResult = { headers: ([string, string])[] | null; uri: string | null; status: number | null; body: number[] | null; dropped: boolean }

const ARGS_MAP = { '':'{"broadcast_theme":["is_dark"],"emit_breakpoint_hit":["id","bp_type","event"],"export_ca_cert":[],"export_settings":["settings"],"get_ca_cert":[],"get_event_by_id":["id"],"get_local_ip":[],"get_settings":[],"import_settings":[],"is_blocked":[],"is_ssl_intercept_enabled":[],"open_detached_window":["label","title","url"],"reset_settings":[],"save_settings":["settings"],"start_proxy":["port"],"stop_proxy":[],"submit_breakpoint_resolution":["id","modified_event"],"toggle_blocked":["enabled"],"toggle_ssl_intercept":["enabled"],"trigger_breakpoint_sync":[]}', 'events':'{"breakpoint_hit":["id","bp_type","event"],"breakpoint_resolved_signal":["id","modified_event"],"proxy_event":["event"],"sync_requested":[],"theme_changed":["is_dark"],"window_closed":["label"]}', 'scripts':'{"set_script_patterns":["patterns"],"submit_script_result":["script_id","result"],"toggle_scripting":["enabled"]}' }
export type Router = { "": {broadcast_theme: (isDark: boolean) => Promise<null>, 
emit_breakpoint_hit: (id: string, bpType: string, event: ProxyEvent) => Promise<null>, 
export_ca_cert: () => Promise<null>, 
export_settings: (settings: AppSettings) => Promise<null>, 
get_ca_cert: () => Promise<string | null>, 
get_event_by_id: (id: string) => Promise<HistoryEntry | null>, 
get_local_ip: () => Promise<string>, 
get_settings: () => Promise<AppSettings>, 
import_settings: () => Promise<AppSettings | null>, 
is_blocked: () => Promise<boolean>, 
is_ssl_intercept_enabled: () => Promise<boolean>, 
open_detached_window: (label: string, title: string, url: string) => Promise<null>, 
reset_settings: () => Promise<AppSettings>, 
save_settings: (settings: AppSettings) => Promise<null>, 
start_proxy: (port: number) => Promise<null>, 
stop_proxy: () => Promise<null>, 
submit_breakpoint_resolution: (id: string, modifiedEvent: ProxyEvent | null) => Promise<null>, 
toggle_blocked: (enabled: boolean) => Promise<null>, 
toggle_ssl_intercept: (enabled: boolean) => Promise<null>, 
trigger_breakpoint_sync: () => Promise<null>},
"events": {breakpoint_hit: (id: string, bpType: string, event: ProxyEvent) => Promise<void>, 
breakpoint_resolved_signal: (id: string, modifiedEvent: ProxyEvent | null) => Promise<void>, 
proxy_event: (event: ProxyEvent) => Promise<void>, 
sync_requested: () => Promise<void>, 
theme_changed: (isDark: boolean) => Promise<void>, 
window_closed: (label: string) => Promise<void>},
"scripts": {set_script_patterns: (patterns: string[]) => Promise<null>, 
submit_script_result: (scriptId: string, result: ScriptResult) => Promise<null>, 
toggle_scripting: (enabled: boolean) => Promise<null>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
