mod cert;
mod procs;
mod proxy;
mod settings;

use procs::{Api, ApiImpl, Events, EventsImpl, Scripts, ScriptsImpl};
use proxy::ProxyState;
use tauri::Manager;
use taurpc::Router;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub async fn run() {
    // ProxyState is Clone and all its fields are Arc<...>, so cloning
    // gives both handlers the *same* underlying shared state.
    let state = ProxyState::default();

    let router = Router::new()
        .export_config(
            specta_typescript::Typescript::default()
                .header("// This file has been generated by Specta. DO NOT EDIT.\n")
                .bigint(specta_typescript::BigIntExportBehavior::String),
        )
        .merge(
            ApiImpl {
                state: state.clone(),
            }
            .into_handler(),
        )
        .merge(
            ScriptsImpl {
                state: state.clone(),
            }
            .into_handler(),
        )
        .merge(
            EventsImpl.into_handler(),
        );

    tauri::Builder::default()
        .plugin(tauri_plugin_log::Builder::new()
            .level(log::LevelFilter::Info)
            .level_for("hudsucker", log::LevelFilter::Off)
            .level_for("hyper", log::LevelFilter::Off)
            .level_for("h2", log::LevelFilter::Off)
            .level_for("rustls", log::LevelFilter::Off)
            .level_for("tokio_util", log::LevelFilter::Off)
            .level_for("tokio_graceful", log::LevelFilter::Off)
            .level_for("tracing", log::LevelFilter::Off)
            .build())
        .plugin(tauri_plugin_opener::init())
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::Destroyed = event {
                // Emit a GLOBAL event via AppEvents trigger
                let trigger = procs::AppEvents::new(window.app_handle().clone());
                let _ = trigger.window_closed(window.label().to_string());
            }
        })
        .setup({
            let state = state.clone();
            move |app| {
                *state.app_handle.lock().unwrap() = Some(app.handle().clone());
                Ok(())
            }
        })
        .invoke_handler(router.into_handler())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
